/**
 * data/snapshot.ts
 *
 * Build-time market data snapshot.
 *
 * Generated by `scripts/fetch-market-data.mjs` (run via `prebuild`).
 * Bundled into the app at build time so GitHub Pages can serve it without
 * any runtime CORS / proxy dependency.
 *
 * The snapshot is the PRIMARY source at runtime. Live fetching is no longer
 * attempted from the browser. Refresh cadence = deploy cadence (a daily GH
 * Actions cron rebuilds and re-deploys).
 */
import snapshotJson from './snapshot.json'

export interface MarketSnapshot {
  schemaVersion: number
  fetchedAt: string
  fxRates: Record<string, number>
  cpiByCountry: Record<string, number>
}

export const SNAPSHOT: MarketSnapshot = snapshotJson as MarketSnapshot

/** FX rates from the snapshot. Always includes EUR = 1. */
export function getSnapshotFxRates(): Record<string, number> {
  return SNAPSHOT.fxRates
}

/**
 * CPI rate (decimal, e.g. 0.0285 for 2.85%) for a country code.
 * Returns null if the snapshot does not include this country (e.g. fetch
 * failed at build time and there was no previous value to reuse).
 */
export function getSnapshotCpi(countryCode: string): number | null {
  const v = SNAPSHOT.cpiByCountry[countryCode]
  return typeof v === 'number' ? v : null
}

/** ISO timestamp of when the snapshot was generated at build time. */
export function getSnapshotFetchedAt(): string {
  return SNAPSHOT.fetchedAt
}
